Rearrange header file ordering for Hamlib 4.0
A recent change to Hamlib 4.0's rig.h file that defines local sleep()
and usleep() macros caused a compile error of the form:

  CC       readcabrillo.o
In file included from ../../tlf/src/globalvars.h:7,
                 from ../../tlf/src/readcabrillo.c:24:
/home/nate/local/include/hamlib/rig.h:108:3: error: expected identifier or ‘(’ before ‘do’
   do {\
   ^~
/home/nate/local/include/hamlib/rig.h:113:5: error: expected identifier or ‘(’ before ‘while’
   } while(0)
     ^~~~~
/home/nate/local/include/hamlib/rig.h:99:3: error: expected identifier or ‘(’ before ‘do’
   do {\
   ^~
/home/nate/local/include/hamlib/rig.h:106:5: error: expected identifier or ‘(’ before ‘while’
   } while(0)
     ^~~~~

Reordering the local includes to follow the system includes allows the
build to proceed.  I don't know why...