Fix a plethora of -Werror=format-security errors with mvprintw()
In all these places a non-constant is used as a format string which
gcc 11 complains about. Fix by using "%s" as format.

audio.c: In function ‘recordmenue’:
audio.c:50:9: error: format not a string literal and no format arguments [-Werror=format-security]
   50 |         mvprintw(j, 0, backgrnd_str);
      |         ^~~~~~~~