Update dxcc prefix_add() to parse overrides lat/lon.
The modification causes strchr() to start looking for the '/' separator
between lat/lon 1 character *after* loc, which has just been overwritten
with a NULL on the line before.

This addresses this test failure:

[ RUN      ] test_add_prefix_check_overrides
[  ERROR   ] --- inf != 44.40000
[   LINE   ] --- test_dxcc.c:97: error: Failure!
[  FAILED  ] test_add_prefix_check_overrides
[==========] tests: 10 test(s) run.
[  PASSED  ] 9 test(s).
[  FAILED  ] tests: 1 test(s), listed below:
[  FAILED  ] test_add_prefix_check_overrides

 1 FAILED TEST(S)
FAIL run_dxcc (exit status: 1)